=== xpf332211/X-RPC/xrpc-framework/xrpc-core/src/main/java/com/meiya/builder/xml/xrpc-bootstrap-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

               Copyright 2009-2016 the original author or authors.

               Licensed under the Apache License, Version 2.0 (the "License");
               you may not use this file except in compliance with the License.
               You may obtain a copy of the License at

                  http://www.apache.org/licenses/LICENSE-2.0

               Unless required by applicable law or agreed to in writing, software
               distributed under the License is distributed on an "AS IS" BASIS,
               WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
               See the License for the specific language governing permissions and
               limitations under the License.

        -->
        <!ELEMENT configuration ANY>

        <!ELEMENT port ANY>

        <!ELEMENT applicationName ANY>

        <!ELEMENT registryConfig ANY>
        <!ATTLIST registryConfig
                connect CDATA #REQUIRED>

        <!ELEMENT serializeType (#PCDATA)>
        <!ATTLIST serializeType
                type CDATA #IMPLIED>

        <!ELEMENT serializer ANY>
        <!ATTLIST serializer
                class CDATA #REQUIRED
                name CDATA #REQUIRED
                num CDATA #REQUIRED>

        <!ELEMENT compressType (#PCDATA)>
        <!ATTLIST compressType
                type CDATA #IMPLIED>

        <!ELEMENT compressor ANY>
        <!ATTLIST compressor
                class CDATA #REQUIRED
                name CDATA #REQUIRED
                num CDATA #REQUIRED>

        <!ELEMENT loadBalanceType (#PCDATA)>
        <!ATTLIST loadBalanceType
                type CDATA #IMPLIED>

        <!ELEMENT loadBalancer ANY>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED>

        <!ELEMENT idGenerator ANY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED>

=== xpf332211/X-RPC/xrpc-demo/xrpc-consumer/src/main/resources/application.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE configuration
        SYSTEM "xrpc-framework/xrpc-core/src/main/java/com/meiya/builder/xml/xrpc-bootstrap-config.dtd">
<configuration>


    <applicationName>app-consumer-name</applicationName>

    <registryConfig connect="zookeeper://127.0.0.1:2181"/>

    <!--    三选一  优先级:自定义class > 带参数 > 文本 -->
    <serializeType type="hessian"/>
    <serializeType>json</serializeType>
    <serializer class="com.meiya.serializer.impl.HessianSerializer2" name="hessian2" num="4"/>

    <compressType>gzip</compressType>

    <loadBalancer class="com.meiya.loadbalancer.impl.ShortestResponseTimeLoadBalancer"/>


    <idGenerator class="com.meiya.utils.IdGenerator" dataCenterId="3" machineId="4"/>
</configuration>

=== xpf332211/X-RPC/xrpc-framework/xrpc-core/src/main/resources/application.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE configuration
        SYSTEM "xrpc-framework/xrpc-core/src/main/java/com/meiya/builder/xml/xrpc-bootstrap-config.dtd">
<configuration>


    <port>8082</port>

    <applicationName>app-default-name</applicationName>

    <registryConfig connect="zookeeper://127.0.0.1:2181"/>

<!--    三选一  优先级:自定义class > 带参数 > 文本 -->
    <serializeType type="hessian"/>
    <serializeType>json</serializeType>
    <serializer class="com.meiya.serialize.impl.HessianSerializer" name="hessian" num="4"/>

    <compressType>gzip</compressType>
    <compressor class="com.meiya.compress.impl.GzipCompressor" name="gzip" num="4"/>
    <compressType>gzip</compressType>





    <idGenerator class="com.meiya.utils.IdGenerator" dataCenterId="3" machineId="4"/>
</configuration>
